"""new seed data

Revision ID: d75057ee0a81
Revises: 15736e78192e
Create Date: 2022-03-07 09:34:57.009124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75057ee0a81'
down_revision = '15736e78192e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cheatsheets', 'media_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('steps', 'media_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'media_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cheatsheets', 'media_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
